version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # Use a stable version, not 3.13
  jobs:
    pre_build: []
    post_build: []

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
